---
    chrome:
        defaultVersion: "68.0"
        path: /
        meta: 
          labels:
          environment: production
          app: projectx
        spec:
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          hostAliases:
          - ip: "127.0.0.1"
            hostnames:
              - "foo.local"
              - "bar.local"
          - ip: "10.1.2.3"
            hostnames:
              - "foo.remote"
              - "bar.remote"
          env:
          - name: TZ
            value: Europe/Kiev
          - name: SCREEN_RESOLUTION
            value: 1920x1080x24
          - name: ENABLE_VNC
            value: 'true'    
          nodeSelector:
            nodeType: N2D
        volumes:
          - name: simple-vol
            emptyDir: {}
        versions: 
          '68.0':
            image: selenoid/vnc:chrome_68.0
            meta:
              labels:
              environment: qa
            volumeMounts:
              - name: simple-vol
                mountPath: /var/simple
            spec:
              resources:
                requests:
                  memory: "1000Mi"
                  cpu: "0.5"
                limits:
                  memory: "1Gi"
                  cpu: "1.5"
          '86.0':
            image: selenoid/vnc:chrome_86.0
            meta:
              labels:
              environment: dev
            spec:
              resources:
                requests:
                  memory: "1000Mi"
                  cpu: "0.5"
                limits:
                  memory: "1Gi"
                  cpu: "1.5"
    firefox:
        defaultVersion: "0"
        path : /wd/hub
        versions: 
          '45.0':
            image: selenoid/vnc:firefox_45.0
          '47.0':
            image: selenoid/vnc:firefox_45.0
    opera:
        path : /
        versions: 
          '66.0':
            image: selenoid/vnc:opera_66.0
          '71.0':
            image: selenoid/vnc:opera_71.0

    android:
        defaultVersion: "8.1"
        #path: "/"
        kernelCaps:
          - SYS_ADMIN
        volumes:
          - name: kvm
            hostPath:
              path: /dev/kvm
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          privileged: true
          capabilities:
            add:
            - net_raw
            - NET_ADMIN
        versions:
          '8.1':
            image: selenoid/android:8.1
            port: 4444
            spec:
              #securityContext:
                #allowPrivilegeEscalation: true
                #readOnlyRootFilesystem: false
                #privileged: true
                #capabilities:
                  #add:
                  #- net_raw
                  #- NET_ADMIN

              resources:
                requests:
                  cpu: 1
                  memory: 2G
                  #devices.kubevirt.io/kvm: "1"
                limits:
                  cpu: 1
                  memory: 2G
                  #devices.kubevirt.io/kvm: "1"

              volumeMounts:
                - mountPath: /dev/kvm
                  name: kvm

